### ISSUE TITLE
Upload welldone-software/pino-http to npm for offline usage

### ISSUE THREAD

**Issue by gioragutt** [welldone-software/node-toolbelt#17]
When using an offline registry and trying to use `node-toolbelt`, the fact that your fork of [`pino-http`](https://github.com/welldone-software/node-toolbelt/blob/master/package.json#L32) is connected via a git link, it doesn't download it with offline registries such as `verdaccio`.

If it was uploaded to npm and references as a normal `npm` module, it would reduce complications of using it offline.

**Comment by EladHeller** [comment]
Fixes in version 1.6.2
